[tool.ruff]
line-length = 120
lint.select = ["E", "F", "I", "B"]
lint.ignore = ["E501", "B008"]
exclude = ["resources/scripts/util*", ".venv", "temp"]

[tool.pyright]
venv = ".venv"
venvPath = "."
stubPath = "./stubs"
